# Generated by Django 3.2.4 on 2021-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_images',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
